### ISSUE TITLE
Shorten "notes" to one char

### ISSUE THREAD

**Issue by ghost91-** [fsimphy/canteenmenu#1]
Mutli-char `notes` (csv: `kennz.`) break much of our layout. They should be replaced with a decent Unicode character. The following are currently known:

 - vegan: `VG`, replace with `NORTH EAST POINTING LEAF` (U+1F652)
 - mensa vital: `MV`, replace with `MONEY BAG ` (U+1F4B0)

And, for the Lulz:
 - chicken: `G` replace with `chicken` or `turkey`
 - pork: `S` replace with `pig` or `pig face`
 - alcohol: `A` (?) replace with `wine glass`

if supported by fira.

**Comment by ghost91-** [comment]
My quick tests showed that fira mono does not support any of these characters (not even `NORTH EAST POINTING LEAF` and `MONEY BAG`) . Could you check that @pheerai?

**Comment by pheerai** [comment]
It looks as if Firo Mono has a quite limited set of chars.

But as we are taking about visual representations, maybe look at Fira Sans which officially supports the full Unicode 4.1 Range [[1]](https://carrois.com/typefaces/FiraSans/#!layout=specimen)

Here are some more facts:
 - `NORTH EAST POINTING LEAF` is in the `Ornamental Dinbats` range, introduced in Unicode 7.
 - `MONEY BAG`, `PIG`, `PIG FACE`, `WINE GLASS` and `CHICKEN` are in the `Miscellaneous Symbols and Pictographs` range, introduced in Unicode 6 and extended since then.
 - `TURKEY` is in the `Supllmenental Symbols and Pictographs` range, first introduced in Unicode 7 and extended since then.

However, it might still be possible that they are available from Fira Sans.

**Comment by ghost91-** [comment]
I can't get any of them to work with the Fira Sans installed via pacman (otf-fira-sans).

**Comment by pheerai** [comment]
I took a look at the fonts available at google fonts (~850), and none of them seems to support `NORTH EAST POINTING LEAF`.

**Comment by ghost91-** [comment]
It looks like this is very difficult to implement, as no font properly supports the characters we need. I will close this as won't fix for now. If anybody has a good idea (or font) for this, feel free to reopen this or create a new issue.
